require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe RideOffersController, type: :controller do
  login_user

  # This should return the minimal set of attributes required to create a valid
  # RideOffer. As you add validations to RideOffer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      origin: "Origin",
      destination: "Destination",
      no_of_people: 2,
      take_off: Time.current
    }
  }

  let(:invalid_attributes) {
    {
      origin: "Origin",
      destination: "",
      no_of_people: 0,
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RideOffersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      get :index
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      ride_offer = @user.ride_offers.create! valid_attributes
      get :show, params: {id: ride_offer.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      ride_offer = @user.ride_offers.create! valid_attributes
      get :edit, params: {id: ride_offer.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RideOffer" do
        expect {
          post :create, params: {ride_offer: valid_attributes}, session: valid_session
        }.to change(RideOffer, :count).by(1)
      end

      it "redirects to the created ride_offer" do
        post :create, params: {ride_offer: valid_attributes}, session: valid_session
        expect(response).to redirect_to(ride_offers_path)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {ride_offer: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          origin: "Kampala",
          destination: "Gulu",
          no_of_people: 2,
          take_off: Time.current
        }
      }

      it "updates the requested ride_offer" do
        ride_offer = @user.ride_offers.create! valid_attributes
        put :update, params: {id: ride_offer.to_param, ride_offer: new_attributes}, session: valid_session
        ride_offer.reload
        expect(ride_offer.destination).to eq(new_attributes[:destination])
      end

      it "redirects to the ride_offer" do
        ride_offer = @user.ride_offers.create! valid_attributes
        put :update, params: {id: ride_offer.to_param, ride_offer: valid_attributes}, session: valid_session
        expect(response).to redirect_to(ride_offers_path)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        ride_offer = @user.ride_offers.create! valid_attributes
        put :update, params: {id: ride_offer.to_param, ride_offer: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ride_offer" do
      ride_offer = @user.ride_offers.create! valid_attributes
      expect {
        delete :destroy, params: {id: ride_offer.to_param}, session: valid_session
      }.to change(RideOffer, :count).by(-1)
    end

    it "redirects to the ride_offers list" do
      ride_offer = @user.ride_offers.create! valid_attributes
      delete :destroy, params: {id: ride_offer.to_param}, session: valid_session
      expect(response).to redirect_to(ride_offers_url)
    end
  end

end
